[package]
name = "styrene-mobile-android"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
dioxus = { workspace = true, features = ["launch", "mobile"] }
styrene-mobile = { path = "../mobile" }

[lints]
workspace = true
